apiVersion: v1
data:
  NODE_ENV: production
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: node-docker-env-app-production-env
  name: docker-env-app-production-env
